name: '⭐Publish Infra'

on:
  workflow_dispatch:

  push:
    branches:
      - main

env:
    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    RESOURCE_GROUP_NAME : 'rg-challenge-2'
    STORAGE_ACCOUNT_NAME : 'stachallenge2'
  
# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_infra:
    permissions:
      id-token: write
      packages: read
      contents: read
    runs-on: ubuntu-20.04
    name: '🕹️ Deploy Infra'
    steps:

      # Login to Azure
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          
          
       # Create Azure Resource Group
      - name: Create resource group
        run: |
          if [ $(az group exists --name ${{ env.RESOURCE_GROUP_NAME }}) = false ]; then
            az group create -n ${{ env.RESOURCE_GROUP_NAME }} -l westeurope --subscription ${{ env.ARM_SUBSCRIPTION_ID }}
          else
            echo "Resource Group ${{ env.RESOURCE_GROUP_NAME }} already exists or name not available"
          fi
        
      # Create Azure Storage Account
      - name: Create storage account
        run: |
          if [ $(az storage account check-name --name ${{ env.STORAGE_ACCOUNT_NAME }} --query "nameAvailable") = true ]; then
            az storage account create -n ${{ env.STORAGE_ACCOUNT_NAME }} -g ${{ env.RESOURCE_GROUP_NAME }} -l northeurope \
                                      --sku Standard_GRS --allow-blob-public-access false
          else 
            echo "Storage Account ${{ env.STORAGE_ACCOUNT_NAME }} already exists or name not available"
          fi
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1


