name: '⭐Publish Infra'

on:
  workflow_dispatch:

  push:
    # branches:
    #   - main

env:
    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    RESOURCE_GROUP_NAME : 'rg-challenge-2'
    STORAGE_ACCOUNT_NAME : 'stachallenge2'
    FUNC_APP_NAME : 'nopasswordteam'
    REGION : 'northeurope'
  
# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: root
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

 #   - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
 #     uses: actions/setup-dotnet@v1
 #     with:
 #       dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './IceCreams.Ratings'
        dotnet build --configuration Release --output '${{ github.workspace }}/output'
        popd

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
      # Artifact name
        name: IceCreams_Ratings
        path: '${{ github.workspace }}/output'

  deploy_infra:
    needs: build
    environment: root
    permissions:
      id-token: write
      packages: read
      contents: read
    runs-on: ubuntu-20.04
    name: '🕹️ Deploy Infra'
    steps:

      # Login to Azure
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

       # Create Azure Resource Group
      - name: Create resource group
        run: |
          az group create -n ${{ env.RESOURCE_GROUP_NAME }} -l westeurope --subscription ${{ env.ARM_SUBSCRIPTION_ID }}
          az storage account create -n ${{ env.STORAGE_ACCOUNT_NAME }} -g ${{ env.RESOURCE_GROUP_NAME }} -l ${{ env.REGION }} \
                                      --sku Standard_GRS --allow-blob-public-access false
          az functionapp create --resource-group ${{ env.RESOURCE_GROUP_NAME }} --consumption-plan-location ${{ env.REGION }} --runtime dotnet-isolated --functions-version 3 --name ${{ env.FUNC_APP_NAME }} --storage-account ${{ env.STORAGE_ACCOUNT_NAME }}

      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          name: IceCreams_Ratings
          path: '${{ github.workspace }}/output'

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNC_APP_NAME }}
          package: '${{ github.workspace }}/output'

